ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS ingredients TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS weight VARCHAR(50);
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS calories INT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS proteins NUMERIC(5,1);
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS fats NUMERIC(5,1);
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS carbs NUMERIC(5,1);
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS cook_time VARCHAR(50);
